### ISSUE TITLE
Library chokes on milliseconds/frames/ticks

### ISSUE THREAD

**Issue by medeaoblongata** [toutpt/captionstransformer#3]
It's neither unusual, nor beyond the specifications for ttml time attributes to include sub-second values (milliseconds, frames, ticks...), but captionstransformer fails to parse these. 

Adobe Premiere (for example) includes sub-second values in its timecodes. And while it's not optimized for captions, it's in very common use, and not a wholly unusual source of ttml files.

Looking under the hood, I can see that ttml.py is only looking for '%H:%M:%S' causing the exception "ValueError unconverted data remains".

The %f macro was added to strftime/strptime in python 2.6 to handle these units. 

You can change ttml.py so that if the conversion fails it will try to convert again, using the %f macro. Something like this:

```
    def get_date(self, time_str):
        try:
            convertedTime = datetime.strptime(time_str, '%H:%M:%S')
        except ValueError as v:
            ulr = len(v.args[0].partition('unconverted data remains: ')[2])
            if ulr:
                convertedTime = datetime.strptime(time_str, "%H:%M:%S.%f")
            else:
                raise v
        return convertedTime
```

It would be wise to add the %f macro to the Writer output as well

```
class Writer(core.Writer):
    DOCUMENT_TPL = u"""<tt xml:lang="" xmlns="http://www.w3.org/ns/ttml"><body><div>%s</div></body></tt>"""
    CAPTION_TPL = u"""<p begin="%(start)s" end="%(end)s">%(text)s</p>"""

    def format_time(self, caption):
        """Return start and end time for the given format"""
        #milliseconds now given (remove the [:-3] for microseconds)
        return {'start': caption.start.strftime('%H:%M:%S.%f')[:-3],
                'end': caption.end.strftime('%H:%M:%S.%f')[:-3]}
```

**Comment by toutpt** [comment]
Please go ahead and give me your pypi ID.  so you can do the release on it
